version: "3.1"
services:
  postgres:
    image: "postgres:14"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: app
      POSTGRES_DB: db
  app:
    build: .
    depends_on:
      - "postgres"
    links:
      - "postgres"
    environment:
      DATABASE_PASSWORD: 'password'
      USER_DATABASE: 'app'
      DATABASE_NAME: 'db'
      DATABASE_HOST: 'postgres'
      PORT: 3000
      WEBHOOK: 'https://discord.com/api/webhooks/842051853298171944/khcRVBPEP12sDkwbQDwXRQJa2SsuAVwBK-hh-mSkcnsc2B-FI4b3HK5tNen2rsalD73N'
      WEBHOOK_WORDLE: 'https://discord.com/api/webhooks/842051853298171944/khcRVBPEP12sDkwbQDwXRQJa2SsuAVwBK-hh-mSkcnsc2B-FI4b3HK5tNen2rsalD73N'
      MIN_HOURS: 9
    ports:
      - '3000:3000'
    command: npm start